name: Build and Test

on: 
  workflow_dispatch:
  push:
    branches:
     - "main"
    paths:
      - "src/**"
jobs:
  build_test_deploy_channel_provider:
    uses: transmitly/transmitly/.github/workflows/build-and-deploy-channel-provider-group.yml@test/dynamic-versioning-build
    with: 
      channelProviderName: Transmitly.ChannelProvider.SendGrid
      channelProviderTypeName: Sdk
    secrets: inherit

      
